### PR TITLE
Hanami 1.3

### PR DESCRIPTION
**Pull request by jodosha**

### CODE REVIEW

**Comment by jodosha** [comment]
@davydovanton First CI error was due to mismatch between Ruby versions in `Gemfile` and `.travis.yml`. By fixing it, it crashed with another error, that is is non-sense.

```
Downloading hanami-1.3.1 revealed dependencies not in the API or the lockfile
(hanami-validations (~> 1.3)).
Either installing with `--full-index` or running `bundle update hanami` should
fix the problem.
The command "eval bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle} " failed. Retrying, 2 of 3.
```

See https://travis-ci.org/hanami/contributors/builds/559398741

---

Can you please download locally this branch and tell me if `bundle install` works for you? Thanks.

**Comment by jodosha** [comment]
I mistakenly committed to `Gemfile.lock` a local version of `hanami-validations`, which had a different requirement from the official release on Rubygems. That was the cause of the CI error.

**Comment by jodosha** [comment]
@mereghost Thanks for the merge, did you deployed it?

**Comment by davydovanton** [comment]
@jodosha I thought that we have automatically commit deployment in CI but no 😞 I think we need to add it. I'll push current master to heroku

**Comment by davydovanton** [comment]
@jodosha done, all works http://contributors.hanamirb.org

**Comment by jodosha** [comment]
Thank you all! 👍

**Pull request merged**
